<?php

return [

    [
        'name' => 'Bufala, Parma e melone',
        'description' => 'Focaccina multicereale con prosciutto crudo di Parma DOP 18 mesi, melone, mix di pomodori di stagione, rucola e olio evo.',
        'price' => 17.00,
        'image' => 'http://www.sebeto.com/intranet/ftpscambio/fotografier/307D.jpg',
        'visible' => false,
    ],
    [
        'name' => 'Chicken bacon burger',
        'description' => 'Pollo 125g, lattuga, pomodoro, bacon, maionese in pane scottato.',
        'price' => 13.00,
        'image' => 'https://rs-menus-api.roocdn.com/images/162f68eb-997c-49f6-9df8-e019dfb10dd5/image.jpeg?width=560&height=315&auto=webp&format=jpg&fit=crop',
        'visible' => false,
    ],
    [
        'name' => 'Bucket Tender crispy + Hot wings ',
        'description' => '2 pezzi tendere e 3 hot wings.',
        'price' => 15.50,
        'image' => 'https://media.kfc.it/app/uploads/public/626/a6f/f34/thumb_468_800_800_0_0_crop.png',
        'visible' => false,
    ],
    [
        'name' => 'Arista cheese burger',
        'description' => 'Arista fritta, lattuga, pomodoro, edamer, maionese.',
        'price' => 13.00,
        'image' => 'https://rs-menus-api.roocdn.com/images/c8b33710-d75e-4435-8bd6-82704332074a/image.jpeg?width=560&height=315&auto=webp&format=jpg&fit=crop',
        'visible' => false,
    ],
    [
        'name' => 'Steak burger',
        'description' => 'Bistecca di controfiletto, edamer, salsa bbq, bacon in pane scottato.',
        'price' => 15.00,
        'image' => 'https://rs-menus-api.roocdn.com/images/e6658333-171d-4be8-aee6-4bb80a673da6/image.jpeg?width=560&height=315&auto=webp&format=jpg&fit=crop',
        'visible' => false,
    ],
    [
        'name' => 'Pulled pork',
        'description' => 'Maiale sfilacciato, salsa bbq alla mela',
        'price' => 14.00,
        'image' => 'https://rs-menus-api.roocdn.com/images/6ac291f3-08d3-4c4d-a959-50e0ba6f1460/image.jpeg?width=560&height=315&auto=webp&format=jpg&fit=crop',
        'visible' => false,
    ],
    [
        'name' => 'Antipasto di mare',
        'description' => 'Cozze, polpo, aringhe, patate e prezzemolo.',
        'price' => 10.00,
        'image' => 'https://rs-menus-api.roocdn.com/images/d397b5bc-1782-44cd-9572-62d64d56dc76/image.jpeg?width=560&height=315&auto=webp&format=jpg&fit=crop',
        'visible' => false,
    ],
    [
        'name' => 'Astice in burro',
        'description' => 'Astice intero 400/500 gr. Saltato in padella con burro, aglio e prezzemolo.',
        'price' => 27.00,
        'image' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR8cLZiNvt61ef3oIsHMrp0r_rk9kOKMHVAGw&usqp=CAU',
        'visible' => false,
    ],
    [
        'name' => 'Montanara fritta al forno',
        'description' => 'pizzetta fritta e ripassata al forno a legna, ricotta di bufala, pomodorini di Corbara, cacioricotta a scaglie e pesto leggero di basilico',
        'price' => 8.00,
        'image' => 'http://www.sebeto.com/intranet/ftpscambio/fotografier/SF188.jpg',
        'visible' => false,
    ],
    [
        'name' => 'Calamari e zucchine',
        'description' => 'frittura di calamari*, zucchine, salsa tartara, sale e pepe.',
        'price' => 15.00,
        'image' => 'http://www.sebeto.com/intranet/ftpscambio/fotografier/SF212.jpg',
        'visible' => true,
    ],
    [
        'name' => 'Un quarto di pollo coscia intera',
        'description' => 'Fusello e sovracoscia cotti al forno',
        'price' => 5.50,
        'image' => 'https://rs-menus-api.roocdn.com/images/1b71fea1-3010-4a82-9016-4d5e861eaad8/image.jpeg?width=560&height=315&auto=webp&format=jpg&fit=crop',
        'visible' => true,
    ],
    [
        'name' => 'Patata al cartoccio con salsa verde',
        'description' => 'Salsa composta da prezzemolo, olio evo, aceto di vino bianco, sale, aglio, peperoncino steso su una patata cotta al forno.',
        'price' => 3.00,
        'image' => 'https://rs-menus-api.roocdn.com/images/313c0dd9-c6ad-4151-873f-43cb5030e711/image.jpeg?width=560&height=315&auto=webp&format=jpg&fit=crop',
        'visible' => true,
    ],
    [
        'name' => 'Parmigiana di melanzane',
        'description' => 'salsa di pomodoro, provola affumicata, grana e basilico.',
        'price' => 8.50,
        'image' => 'http://www.sebeto.com/intranet/ftpscambio/fotografier/SF094.jpg',
        'visible' => true,
    ],
    [
        'name' => 'Fresellina di mare',
        'description' => 'polpo* all’insalata, olio evo, limone, datterini rossi e gialli e olive nere.',
        'price' => 10.00,
        'image' => 'http://www.sebeto.com/intranet/ftpscambio/fotografier/SF129.jpg',
        'visible' => true,
    ],
    [
        'name' => 'Linguine alla crema di tonno',
        'description' => 'Sapori semplici, ma sfiziosi, che abbiamo voluto riproporre in una chiave incredibilmente cremosa, per questo abbiamo scelto un formato di pasta avvolgente',
        'price' => 8.00,
        'image' => 'https://www.giallozafferano.it/images/253-25314/Linguine-alla-crema-di-tonno_780x520_wm.jpg',
        'visible' => true,
    ],
    [
        'name' => 'Spaghetti Amatriciana',
        'description' => 'Spaghetti, guanciale di Amatrice, pomodori pelati e Pecorino Romano DOP.',
        'price' => 8.00,
        'image' => 'https://www.giallozafferano.it/images/245-24560/Spaghetti-all-Amatriciana_450x300.jpg',
        'visible' => true,
    ],
    [
        'name' => 'Spaghetti Cacio e Pepe',
        'description' => 'Combinazione chimica di acqua e proteine del Pecorino, fondamentale per ottenere una crema senza grumi, i grani di pepe interi schiacciati al momento e tostati in padella per sprigionare tutto il loro profumo pungente.',
        'price' => 8.50,
        'image' => 'https://www.giallozafferano.it/images/219-21989/Spaghetti-Cacio-e-Pepe_450x300.jpg',
        'visible' => true,
    ],
    [
        'name' => 'Pasta alla gricia',
        'description' => 'Rigatoni. Guanciale. Pecorino romani. Pepe. Sale e ninet\'altro',
        'price' => 9.00,
        'image' => 'https://www.giallozafferano.it/images/245-24521/Pasta-alla-gricia_450x300_sp.jpg',
        'visible' => true,
    ],
    [
        'name' => 'Risotto alla salsiccia',
        'description' => 'Il risotto alla salsiccia è uno di quei piatti che fanno fiutare il profumo già dalla porta di casa.',
        'price' => 8.00,
        'image' => 'https://www.giallozafferano.it/images/205-20515/Risotto-alla-salsiccia_450x300.jpg',
        'visible' => true,
    ],
    [
        'name' => 'Calamarata',
        'description' => 'La calamarata, nel napoletano, è conosciuta con il nome di mezzi paccheri.',
        'price' => 15.00,
        'image' => 'https://www.giallozafferano.it/images/230-23006/Calamarata_450x300.jpg',
        'visible' => true,
    ],
    [
        'name' => 'Spaghetti alla puttanesca',
        'description' => 'Il sapore unico degli spaghetti alla puttanesca è dato dal sapido condimento che li avvolge: pomodori pelati, olive di Gaeta, capperi e filetti di alici.',
        'price' => 10.00,
        'image' => 'https://www.giallozafferano.it/images/239-23911/Spaghetti-alla-puttanesca_450x300.jpg',
        'visible' => true,
    ],
    [
        'name' => 'Vellutata di porri con crostini saporiti',
        'description' => 'Una ricetta realizzata con ingredienti genuini, semplice da realizzare e cotta lentamente per amalgamare i sapori e far ammorbidire le verdure.',
        'price' => 7.00,
        'image' => 'https://www.giallozafferano.it/images/151-15175/Vellutata-di-porri-con-crostini-saporiti_780x520_wm.jpg',
        'visible' => true,
    ],
    [
        'name' => 'Petti di pollo al latte',
        'description' => 'I petti di pollo al latte sono un\'idea alternativa alle classiche scaloppine',
        'price' => 11.00,
        'image' => 'https://www.giallozafferano.it/images/239-23966/Petti-di-pollo-al-latte_450x300.jpg',
        'visible' => true,
    ],
    [
        'name' => 'Carne alla pizzaiola',
        'description' => 'Pomodoro, aglio e origano sono quindi le basi del condimento in cui vengono immerse le fettine di vitello o di manzo.',
        'price' => 11.00,
        'image' => 'https://www.giallozafferano.it/images/242-24229/Carne-alla-pizzaiola_450x300.jpg',
        'visible' => true,
    ],
    [
        'name' => 'Cotoletta alla palermitana',
        'description' => 'La cotoletta solitamente è una pietanza molto amata dai bambini.',
        'price' => 11.00,
        'image' => 'https://www.giallozafferano.it/images/28-2897/Cotoletta-alla-palermitana_780x520_wm.jpg',
        'visible' => true,
    ],
    [
        'name' => 'Bombette pugliesi',
        'description' => 'Le bombette pugliesi sono un secondo piatto di carne tipico della cucina pugliese e consistono in involtini di vitello  ripieni o in alcuni casi avvolti da pancetta, con un cuore saporito di caciocavallo.',
        'price' => 11.00,
        'image' => 'https://www.giallozafferano.it/images/17-1753/Bombette-pugliesi_780x520_wm.jpg',
        'visible' => true,
    ],
    [
        'name' => 'Frittata al forno con ricotta e spinaci',
        'description' => 'Questa idea della frittata con ricotta e spinaci unisce il gusto leggermente amarognolo degli spinaci con quello morbido della ricotta stessa che alleggerisce la preparazione.',
        'price' => 8.00,
        'image' => 'https://www.giallozafferano.it/images/10-1080/Frittata-al-forno-con-ricotta-e-spinaci_780x520_wm.jpg',
        'visible' => true,
    ],
    [
        'name' => 'Straccetti di manzo',
        'description' => 'Le classiche scaglie di Parmigiano si trasformano in fragranti cialdine che accompagnano questi favolosi straccetti di carne serviti su un letto di rucola.',
        'price' => 9.50,
        'image' => 'https://www.giallozafferano.it/images/166-16638/Straccetti-di-manzo_450x300.jpg',
        'visible' => true,
    ],
    [
        'name' => 'Filetti di salmone alla mediterranea',
        'description' => 'Succosi pomodorini macerati, olive nere e i capperi donano una nota decisa al piatto.',
        'price' => 9.50,
        'image' => 'https://www.giallozafferano.it/images/161-16169/Filetti-di-salmone-alla-mediterranea_780x520_wm.jpg',
        'visible' => true,
    ],
    [
        'name' => 'Souvlaki di maiale',
        'description' => 'Spiedini di carne marinati in un\'emulsione di olio, succo di limone e aromi e poi cotti alla griglia.',
        'price' => 9.00,
        'image' => 'https://www.braciamiancora.com/wp-content/uploads/2018/08/souvlaki.jpg',
        'visible' => true,
    ],
    [
        'name' => 'Involtini in foglie di vite',
        'description' => 'Gli involtini in foglie di vite sono preparati con un ripieno di riso e con le foglie della vite, molto diffusa in Grecia.',
        'price' => 7.00,
        'image' => 'https://images2.corriereobjects.it/methode_image/2016/07/12/Cucina/Foto%20Trattate/dolmadakia_DSCF0056-ksn-U43200944226900rOG-620x385@Cucina-Web.jpg?v=201607121956',
        'visible' => true,
    ],
    [
        'name' => 'Gyros',
        'description' => 'Il gyros è un cibo da strada tipico della Grecia, molto simile al kebab, ripieno di carne di maiale che viene cotta su lunghi spiedi e tagliata in fette sottili.',
        'price' => 4.50,
        'image' => 'https://quieventi.it/wp-content/uploads/2021/09/qui-eventi-regioni-d-europa-gyros.jpg',
        'visible' => true,
    ],
    [
        'name' => 'Insalata greca',
        'description' => 'Gli ingredienti protagonisti di questo celebre piatto greco sono: pomodori, feta, olive (greche naturalmente!), cipolle e cetrioli.',
        'price' => 5.50,
        'image' => 'https://wips.plug.it/cips/buonissimo.org/cms/2011/09/95542957_s.jpg?w=713&a=c&h=407',
        'visible' => true,
    ],
    [
        'name' => 'Moussaka',
        'description' => 'Il tipico sformato di melanzane e carne trita ricoperto con un abbondante strato di besciamella!',
        'price' => 7.50,
        'image' => 'https://inviaggioconlachef.com/wp-content/uploads/2021/12/moussaka.jpeg',
        'visible' => true,
    ],
    [
        'name' => 'Involtini primavera',
        'description' => 'Versione vegetariana farcita con cavolo cappuccio, cipolla e carote',
        'price' => 6.50,
        'image' => 'https://www.giallozafferano.it/images/ricette/230/23004/foto_hd/hd650x433_wm.jpg',
        'visible' => true,
    ],
    [
        'name' => 'Ravioli cinesi al vapore',
        'description' => 'Ravioli di carne, arricchiti con cavolo cappuccio e cipollotto.',
        'price' => 6.00,
        'image' => 'https://inviaggioincucina.com/wp-content/uploads/2021/04/Ravioli-di-gamberi-al-vapore-senza-carne-def.jpg',
        'visible' => true,
    ],
    [
        'name' => 'Pollo alle mandorle',
        'description' => 'Bocconcini di pollo arricchiti con germogli di bambù e avvolti in una deliziosa cremina insaporita con salsa di soia.',
        'price' => 7.50,
        'image' => 'https://blog.giallozafferano.it/cucinaplus/wp-content/uploads/2019/03/DSCF1065-01.jpeg',
        'visible' => true,
    ],
    [
        'name' => 'Maiale in agrodolce',
        'description' => 'Il maiale in agrodolce è una ricetta della tradizione: il verde dei peperoni, il rosso del pomodoro e il giallo dell’ananas, un mix dalle tinte vivaci che, insieme alla salsa agrodolce, conferisce al piatto il suo gusto inconfondibile.',
        'price' => 7.00,
        'image' => 'http://ricettecuco.com/wp-content/uploads/2018/04/Maiale-in-agrodolcericetetcuco.jpg',
        'visible' => true,
    ],
    [
        'name' => 'Riso alla cantonese',
        'description' => 'Riso basmati bollito e poi saltato in padella o Wok con uova strapazzate, piselli, prosciutto.',
        'price' => 7.50,
        'image' => 'https://www.ilcuoreinpentola.it/wp-content/uploads/2020/05/riso-alla-cantonese.jpeg',
        'visible' => true,
    ],
    [
        'name' => 'Lasagne vegetariane',
        'description' => 'Con i suoi gustosi strati di verdure e besciamella, intervallati da sottili veli di buona pasta sfoglia fatta in casa, le lasagne vegetariane sapranno conquistare anche i palati più difficili!',
        'price' => 8.00,
        'image' => 'https://blog.giallozafferano.it/melacannellaefantasia/wp-content/uploads/2018/03/lasagne-vegetariane-1.jpg',
        'visible' => true,
    ],
    [
        'name' => 'Insalata di riso integrale',
        'description' => 'Speciale riso integrale ricco di fibre e dall’alto potere saziante, con piccoli e croccanti semi di zucca, zucchine, carote e pomodorini.',
        'price' => 8.50,
        'image' => 'https://www.dueamicheincucina.it/wp-content/uploads/2018/06/Insalata-di-riso-integrale-nero-con-verdure-e-pollo-e.jpg',
        'visible' => true,
    ],
    [
        'name' => 'Hummus',
        'description' => 'Salsa a base di pasta di ceci e pasta di semi di sesamo (tahina) aromatizzata con olio di oliva, aglio, succo di limone e paprika, semi di cumino in polvere e prezzemolo finemente tritato.',
        'price' => 4.50,
        'image' => 'https://cdn.shopify.com/s/files/1/0568/1541/9601/articles/Hummus_1600x.jpg?v=1660781103',
        'visible' => true,
    ],
    [
        'name' => 'Trenette al pesto, patate e fagiolini',
        'description' => 'Trenette al pesto, patate e fagiolini in olio extravergine d\'oliva ligure.',
        'price' => 7.80,
        'image' => 'https://wips.plug.it/cips/buonissimo.org/cms/2011/10/trenette-al-pesto-e-fagiolini.jpg?w=712&a=c&h=406',
        'visible' => true,
    ],
    [
        'name' => 'Enchiladas',
        'description' => 'Rotolini di tortillas farciti con pollo, sugo di pomodoro, formaggio, peperoncini e panna acida.',
        'price' => 6.80,
        'image' => 'https://www.eatingbirdfood.com/wp-content/uploads/2020/01/healthy-chicken-enchiladas-3.jpg',
        'visible' => true,
    ],
    [
        'name' => 'Burrito',
        'description' => 'Abbiamo realizzato la versione classica del burrito, quella farcita con manzo, fagioli e formaggio.',
        'price' => 4.90,
        'image' => 'https://blog.giallozafferano.it/martolinaincucina/wp-content/uploads/2022/01/Burritos-B1200x1200.jpg',
        'visible' => true,
    ],
    [
        'name' => 'Tacos con carne',
        'description' => 'Croccanti tortillas di mais farcite con tenero manzo sfilacciato, reso ancora più saporito da una lunga marinatura, con l’aggiunta di pomodori e cipollotti.',
        'price' => 5.80,
        'image' => 'https://www.foodblog.it/wp-content/uploads/2020/04/tacos-con-chili-ricetta.jpg',
        'visible' => true,
    ],
    [
        'name' => 'Fagioli alla messicana',
        'description' => 'Fagioli neri con prezzemolo, cannella, cumino e peperoncino fresco.',
        'price' => 7.40,
        'image' => 'https://www.ricettedigusto.info/wp-content/uploads/2013/11/fagioli-alla-messicana-1200x800.jpg',
        'visible' => true,
    ],
    [
        'name' => 'Pizza Margherita',
        'description' => '',
        'price' => 5.00,
        'image' => 'https://cdn.shopify.com/s/files/1/0586/6795/8427/articles/Margherita-9920.jpg?crop=center&height=800&v=1644590028&width=800',
        'visible' => true,
    ],
    [
        'name' => 'Pizza tonno e cipolle',
        'description' => '',
        'price' => 6.00,
        'image' => 'https://blog.giallozafferano.it/cucinoperpassione/wp-content/uploads/2019/09/Pizza-rossa-tonno-e-cipolla.jpg',
        'visible' => true,
    ],
    [
        'name' => 'Pizza capricciosa',
        'description' => '',
        'price' => 6.40,
        'image' => 'https://www.buttalapasta.it/wp-content/uploads/2017/11/pizza-capricciosa.jpg',
        'visible' => true,
    ],
    [
        'name' => 'Pizza quattro stagioni',
        'description' => '',
        'price' => 5.90,
        'image' => 'https://i.pinimg.com/originals/c0/08/db/c008dbe5cdbe24e5fb75054d38aa7a17.jpg',
        'visible' => true,
    ],
    [
        'name' => 'Pizza quattro formaggi',
        'description' => '',
        'price' => 5.50,
        'image' => 'https://blog.giallozafferano.it/zeroglutine/wp-content/uploads/2020/04/IMG_5544-720x411.jpg',
        'visible' => true,
    ],
    [
        'name' => 'Pizza diavola',
        'description' => '',
        'price' => 5.50,
        'image' => 'https://foodandchips.com/wp-content/uploads/2019/02/BFV36537_CC2017_2IngredintDough4Ways-FB.jpg',
        'visible' => true,
    ],
    [
        'name' => 'Pad thai',
        'description' => 'Tipico street food thailandese a base di noodles di riso saltati al momento nel wok con l’aggiunta di gamberi, carne o tofu, oltre che verdure, arachidi, spezie e saporiti condimenti.',
        'price' => 9.80,
        'image' => 'https://fullofplants.com/wp-content/uploads/2022/03/easy-vegan-pad-thai-noodle-dish-with-bean-sprouts-thumb.jpg',
        'visible' => true,
    ],
    [
        'name' => 'Pollo con anacardi',
        'description' => 'Abbiamo puntato sulla sapidità della salsa di soia, all\'immancabile tocco fresco e pungente dello zenzero, che si fondono sapientemente con i teneri bocconcini di pollo e gli anacardi tostati.',
        'price' => 10.50,
        'image' => 'https://blog.giallozafferano.it/cuochinprogress/wp-content/uploads/2019/10/pollo-agli-anacardi1-720x440.jpg',
        'visible' => true,
    ],
    [
        'name' => 'Sticky rice',
        'description' => 'Lo sticky rice è un tradizionale dessert a base di riso e latte di cocco, guarnito con mango fresco.',
        'price' => 8.50,
        'image' => 'https://dolciveloci.it/wp-content/uploads/2019/07/SH_mango_sticky_rice.jpg',
        'visible' => true,
    ],
    [
        'name' => 'Tagliata di manzo ai due curry',
        'description' => 'Piatto a base di carne, caratterizzato da una breve cottura e dal suo color rosato all\'interno, con due livelli diversi di piccantezza.',
        'price' => 12.00,
        'image' => 'https://www.giallozafferano.it/images/194-19437/Tagliata-di-manzo-ai-due-curry_780x520_wm.jpg',
        'visible' => true,
    ],
    [
        'name' => 'Curry verde Thai',
        'description' => 'Delizioso piatto unico thailandese, composto da manzo e verdure che vengono cotte in un saporito latte di cocco aromatizzato al curry verde.',
        'price' => 12.00,
        'image' => 'https://www.giallozafferano.it/images/16-1675/Curry-verde-Thai_450x300.jpg',
        'visible' => true,
    ],
    [
        'name' => 'Sushi',
        'description' => 'Riso acidulato con aceto di riso, pesce crudo, alghe, zenzero, wasabi, soia.',
        'price' => 11.00,
        'image' => 'https://www.riomare.it/wp-content/uploads/2020/03/sushi.jpg',
        'visible' => true,
    ],
    [
        'name' => 'Tempura',
        'description' => 'Tempura di verdure e di crostacei accompagnata con salsa agrodolce tentsuyu, insieme a daikon e zenzero grattugiato.',
        'price' => 10.00,
        'image' => 'https://i.pinimg.com/originals/5d/53/3e/5d533e8af2a2cc68c7df75e7e2992b97.jpg',
        'visible' => true,
    ],
    [
        'name' => 'Zuppa di noodles',
        'description' => 'Zuppa di fili di pasta all\'uovo, cotti in un profumato brodo di carne e verdura.',
        'price' => 9.00,
        'image' => 'https://www.agrodolce.it/app/uploads/2018/05/zuppa-di-noodles_A1768.jpg',
        'visible' => true,
    ],
    [
        'name' => 'Uramaki california roll',
        'description' => 'Il california roll è preparato con polpa di granchio cotta, avocado e maionese.',
        'price' => 12.00,
        'image' => 'https://www.sidechef.com/recipe/8f379697-7d39-4f61-a336-fd4134eeee18.jpg?d=1408x1120',
        'visible' => true,
    ],
    [
        'name' => 'Kebab',
        'description' => 'Kebab roll con carne',
        'price' => 5.00,
        'image' => 'https://media.istockphoto.com/id/1127711790/photo/tortilla-wrap-with-fried-chicken-meat-and-vegetables.jpg?s=612x612&w=0&k=20&c=CUJMZTwADAwRAx9_AkMMTTQxCUdfty4TlbH4nAyEgfQ=',
        'visible' => true,
    ],
    [
        'name' => 'Piatto Kebab',
        'description' => 'Piatto kebab con carne, verdure e patatine fritte.',
        'price' => 7.80,
        'image' => 'https://1.bp.blogspot.com/-33j5wRZjuNA/YPwn7oOpo3I/AAAAAAAAvZQ/YoWuTv4HIS43OTtbeMLdYQgYlxaTHzp-QCPcBGAsYHg/s4096/IMG_20210724_132418998_PORTRAIT.jpg',
        'visible' => true,
    ],
    [
        'name' => 'Piadina Kebab',
        'description' => 'Piadina ripiena di carne, verdure e patatine fritte.',
        'price' => 6.00,
        'image' => 'https://www.leidonnaweb.it/media/k2/items/cache/9f61d10d254b0dd13d20a8b04bc2ce8a_XL.jpg',
        'visible' => true,
    ],
    [
        'name' => 'Marinara',
        'description' => 'tipica pizza napoletana realizzata solo con pomodoro fresco, olio, aglio e origano',
        'price' => 5.50,
        'image' => 'https://assets.tmecosys.com/image/upload/t_web767x639/img/recipe/ras/Assets/97C2C718-5015-437F-8355-316EE000F57C/Derivates/556409BB-02E0-4BA3-BC16-F409F609FCED.jpg',
        'visible' => true,
    ],
    [
        'name' => 'Carciofi e pancetta',
        'description' => 'tipica pizza realizzata con carciofi, olio, aglio e pancetta',
        'price' => 8.50,
        'image' => 'https://media-assets.ad-italia.it/photos/60f009487418b0b14e63c64e/16:9/w_1280,c_limit/Schermata-2021-04-17-alle-17.01.36.jpg',
        'visible' => true,
    ],
];
