<?php

return [

    [
        'name' => 'Egg burger',
        'description' => 'Burger, lattuga, pomodoro, uovo, maionese',
    'price' => 13.00,
    'image' => 'https://rs-menus-api.roocdn.com/images/c3ea4cf7-c192-4685-a730-df3a4ee2d993/image.jpeg?width=560&height=315&auto=webp&format=jpg&fit=crop',
    'visible' => true,
    ],
    [
        'name' => 'Chicken bacon burger',
        'description' => 'Pollo, lattuga, pomodoro, bacon, maionese',
        'price' => 13.00,
        'image' => 'https://rs-menus-api.roocdn.com/images/162f68eb-997c-49f6-9df8-e019dfb10dd5/image.jpeg?width=560&height=315&auto=webp&format=jpg&fit=crop',
        'visible' => true,
    ],
    [
        'name' => 'Arista cheese burger',
        'description' => 'Arista fritta, lattuga, pomodoro, edamer, maionese',
        'price' => 13.00,
        'image' => 'https://rs-menus-api.roocdn.com/images/c8b33710-d75e-4435-8bd6-82704332074a/image.jpeg?width=560&height=315&auto=webp&format=jpg&fit=crop',
        'visible' => true,
    ],
    [
        'name' => 'Steak burger',
        'description' => 'Bistecca di controfiletto, edamer, salsa bbq',
        'price' => 15.00,
        'image' => 'https://rs-menus-api.roocdn.com/images/e6658333-171d-4be8-aee6-4bb80a673da6/image.jpeg?width=560&height=315&auto=webp&format=jpg&fit=crop',
        'visible' => true,
    ],
    [
        'name' => 'Pulled pork',
        'description' => 'Maiale sfilacciato, salsa bbq alla mela',
        'price' => 14.00,
        'image' => 'https://rs-menus-api.roocdn.com/images/6ac291f3-08d3-4c4d-a959-50e0ba6f1460/image.jpeg?width=560&height=315&auto=webp&format=jpg&fit=crop',
        'visible' => true,
    ],
    [
        'name' => 'Antipasto di mare extra - 250gr',
        'description' => 'Immergere il prodotto in acqua bollente da congelato per circa 6 minuti, condire con un \'emulsione a fine cottura',
        'price' => '6.63',
        'image' => 'https://rs-menus-api.roocdn.com/images/d397b5bc-1782-44cd-9572-62d64d56dc76/image.jpeg?width=560&height=315&auto=webp&format=jpg&fit=crop',
        'visible' => true,
    ],
    [
        'name' => 'Astice intero - al pezzo',
        'description' => 'Astice intero congelato 400/500 gr. Lasciare scongelare il prodotto in acqua fredda per 1 ora',
        'price' => 19.90,
        'image' => 'https://rs-menus-api.roocdn.com/images/a52a6aa4-8584-4293-b9a9-9dadd32178ef/image.jpeg?width=560&height=315&auto=webp&format=jpg&fit=crop',
        'visible' => true,
    ],
    [
        'name' => 'Bastoncini di pesce - 250gr',
        'description' => 'Fritti o in forno. 8 pezzi circa',
        'price' => 1.47,
        'image' => 'https://rs-menus-api.roocdn.com/images/1d1c8b46-f61a-4f1e-bf47-76df3da376c8/image.jpeg?width=560&height=315&auto=webp&format=jpg&fit=crop',
        'visible' => true,
    ],
    [
        'name' => 'Filetti di acciuga - 250 gr',
        'description' => 'Lasciare scongelare il prodotto sotto acqua fredda per 15/20 minuti',
        'price' => 3.58,
        'image' => 'https://rs-menus-api.roocdn.com/images/22bfa22a-c173-4ee5-a4f5-8a57ea44d83e/image.jpeg?width=560&height=315&auto=webp&format=jpg&fit=crop',
        'visible' => true,
    ],
    [
        'name' => 'Un quarto di pollo coscia intera',
        'description' => 'Fusello e sovracoscia',
        'price' => 5.50,
        'image' => 'https://rs-menus-api.roocdn.com/images/1b71fea1-3010-4a82-9016-4d5e861eaad8/image.jpeg?width=560&height=315&auto=webp&format=jpg&fit=crop',
        'visible' => true,
    ],
    [
        'name' => 'Patata al cartoccio con salsa verde',
        'description' => 'Ingredienti salsa verde: prezzemolo, olio evo, aceto di vino bianco, acciughe sott\'olio, sale, aglio, peperoncino',
        'price' => 3.00,
        'image' => 'https://rs-menus-api.roocdn.com/images/313c0dd9-c6ad-4151-873f-43cb5030e711/image.jpeg?width=560&height=315&auto=webp&format=jpg&fit=crop',
        'visible' => true,
    ],
    [
        'name' => 'Verdure mix',
        'description' => 'Carote e zucchine listarelle',
        'price' => 4.00,
        'image' => 'https://rs-menus-api.roocdn.com/images/983001b1-1d50-4821-8f42-3545249f5cd9/image.jpeg?width=560&height=315&auto=webp&format=jpg&fit=crop',
        'visible' => true,
    ],
    [
        'name' => 'Verza',
        'description' => 'Ripassata con un po\' di aglio',
        'price' => 4.00,
        'image' => 'https://rs-menus-api.roocdn.com/images/1f631a09-cf47-4931-aee4-974f25e585df/image.jpeg?width=560&height=315&auto=webp&format=jpg&fit=crop',
        'visible' => true,
    ],
];